export default users = [
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'a',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'b',
  },
  {
    source: require('../../assets/avatar.png'),
    name: '1Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'c',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: '2ELIOS, Power User',
    city: 'Roma',
    key: 'd',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi Mario Rossi Mario Rossi Mario Rossi',
    status: 'ELIOS, Power User',
    city: '3Roma',
    key: 'e',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'f',
  },
  {
    source: require('../../assets/avatar.png'),
    name: '1Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'g',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: '2ELIOS, Power User',
    city: 'Roma',
    key: 'h',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi Mario Rossi Mario Rossi Mario Rossi',
    status: 'ELIOS, Power User',
    city: '3Roma',
    key: 'k',
  },
  {
    source: require('../../assets/avatar.png'),
    name: 'Mario Rossi',
    status: 'ELIOS, Power User',
    city: 'Roma',
    key: 'l',
  },
];
